version: '3'
services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=enter_password_here
    volumes:
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == docker-node1]
volumes:
  splunk_data:
  splunk_etc:
